Revert "[openmp] Match upstream default for LIBOMP_OMPD_SUPPORT (#3934)"
breaks build of gdb-plugin
llvm-project/openmp/libompd/gdb-plugin/ompdAPITests.c:5:10: fatal error: omp-tools.h: No such file or directory
    5 | #include <omp-tools.h>
      |          ^~~~~~~~~~~~~

This reverts commit 783ea43b41a6a013e221d540307e388b09cd18fd.